version: "3.8"
services:
  database:
    image: postgres:${POSTGRES_VERSION-13}
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./volumes/database/Postgres/init:/docker-entrypoint-initdb.d
      #- ./database/Postgres/data:/var/lib/postgresql/data
    networks:
      - servers
    ports:
      - 5432:5432